#!/bin/bash
#SBATCH -J 2tj
#SBATCH -o x.%j.out
#SBATCH -e x.%j.err
# SBATCH -t 8:00:00
#SBATCH -N 4
#SBATCH --ntasks-per-node=2
#SBATCH --dependency=afterany:21205

module purge
module load gnu openmpi mkl gsl
jdir=/export/data/share/wufeng/share/programs/JDFTX-fix20180209/build/
NCORES=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))

mpirun --mca btl openib,sm,self --bind-to none -n $NCORES $jdir/jdftx -i main.in > main.out 
