#!/bin/bash
#SBATCH --job-name=liccc
#SBATCH --output=x.%j.out
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=7
# SBATCH --time=4:00:00
# SBATCH --dependency=afterany:846

module purge
module load gnu openmpi mkl gsl
jdir=/data/share/wufeng/share/programs/JDFTX-201712-share/build/
NCORES=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))

mpirun --mca btl openib,sm,self --bind-to none -n $NCORES $jdir/jdftx -i main.in > main.out
