#!/bin/bash
#SBATCH --job-name=wk
#SBATCH --output=qe.%j
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=16
#SBATCH --time=24:00:00
#SBATCH --partition=normal
# SBATCH --dependency=afterany:48083
# SBATCH --account=cpuq


 module add intel/17.0.5.239 impi/2017
 NCORES=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))
 MPICMD="mpirun -genv I_MPI_FABRICS shm:ofa -n $SLURM_NTASKS"
 PWDIR="/export/data/share/wufeng/programs-intel2017.5/qe-6.1-scal/bin"

date

$MPICMD $PWDIR/pw.x -nk 2 -nd 1 -inp relax.in > relax.out

date

