#!/bin/bash
#SBATCH --job-name=pwx
#SBATCH --output=qe.%j
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=16
#SBATCH --time=24:00:00
# SBATCH --partition=cpuq
# SBATCH --dependency=afterany:48083
# SBATCH --account=cpuq
# SBATCH --account=cfn307395

 module add intel/17.0.5.239 impi/2017
 export OMP_NUM_THREADS=1
 NCORES=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))
 MPICMD="mpirun -genv I_MPI_FABRICS shm:ofa -n $SLURM_NTASKS"
 PWDIR="/export/data/share/wufeng/programs-intel2017.5/qe-6.1-scal/bin"



echo "Start:"; date

 $MPICMD $PWDIR/pw.x -nk 2 -nb 2 -nd 1 -inp relax.in > relax.out

echo "Done:"; date
