#!/bin/bash
#SBATCH -J eps
#SBATCH -o x.%j.out
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH -t 1:00:00

module purge
module load gnu openmpi mkl gsl
jdir=/export/data/share/yuanping/JDFTXDIR/build
MPICMD="mpirun --mca btl openib,sm,self --bind-to none -n $SLURM_NTASKS"

$MPICMD $jdir/jdftx -i minus.in > minus.out 
$MPICMD $jdir/jdftx -i plus.in > plus.out 
