#!/bin/bash
#SBATCH --job-name=tianpeng
#SBATCH --output=qe.%j
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=01:00:00
#SBATCH --partition=windfall
#SBATCH --dependency=afterany:517
#SBATCH --account=windfall
#SBATCH --mail-user=kli103@ucsc.edu
#SBATCH --mail-type=FAIL

####################### Kairay ###########################################
# echo "Start:"; date
# module add intel/17.0.5.239 impi/2017
# NORES=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))
# MPICMD="mpirun -genv I_MPI_FABRICS shm:ofa -n $SLURM_NTASKS"
# PWDIR="/export/data/share/wufeng/programs-intel2017.5/qe-6.1-scal/bin"
# YAMDIR=/export/data/share/jxu/yambo-codes/yambo-4.1.4/bin
# YAMDIR=/export/data/share/jxu/yambo-codes/yambo-4.4.0/bin
##########################################################################

################### Stampede2 ###########################################
# echo "Start:"; date
# echo "Running program on $SLURM_JOB_NUM_NODES nodes with $SLURM_NTASKS total tasks, with each node getting $SLURM_NTASKS_PER_NODE running on cores."
# export OMP_NUM_THREADS=1
# MPICMD="ibrun"
# YAMDIR=/home1/06931/kli1003/work/yambo_install/yambo-4.1.4/bin
#########################################################################

####################################### Lux #########################################################################################################
 echo "Start:"; date;
 echo "Running program on $SLURM_JOB_NUM_NODES nodes with $SLURM_NTASKS total tasks, with each node getting $SLURM_NTASKS_PER_NODE running on cores."
 module load intel/impi
 export OMP_NUM_THREADS=1
 MPICMD="mpirun -n $SLURM_NTASKS --ppn 40"
 YAMDIR=/data/users/jxu153/codes/yambo/yambo-4.1.4/bin
# YAMDIR=/data/users/jxu153/codes/yambo/yambo-4.4.0/bin
# YAMDIR=/home/kli103/work/programs/yambo-4.4.0/bin
#####################################################################################################################################################

############################### BNL ###########################
# module load intel
# echo "Start:"; date
# export OMP_NUM_THREADS=1
# MPICMD="srun -n $SLURM_NTASKS"
# MPICMDS="mpirun -n 1"
# YAMDIR="/sdcc/u/kli/programs/yambo-4.1.4_feng/bin"
# PWDIR="/sdcc/u/kli/programs/qe-6.1.0/bin"
###############################################################

##########################################################################################################
 mkdir ../data
# go to the directory where PWscf hBN.SAVE is
 cd ../temp/BN.save
 cp ../../job_yambo/init.in0 ./
# Step 1: launch p2y to convert the PWscf hBN.SAVE output to Yambo format
 $MPICMD $YAMDIR/p2y
 
 RL=`grep "Max WF components" l_stderr  | awk '{print $7}'`   # yambo 4.1
# RL=`grep "Max WF components" l-p2y  | awk '{print $7}'`      # yambo 4.4
 RL=`echo "scale=2;$RL/(sqrt(45./15.))^3" | bc -l`
 RL=`echo "$RL/1+1" | bc`
 echo "RL = $RL"
 sed "s/XXX/$RL/g" init.in0 > init.in

# Step 2: launch yambo to run the initialization (setup) runlevel
 $MPICMD $YAMDIR/yambo -F init.in
 
 mv SAVE ../../data; mv LOG ../../data; mv r_setup ../../data
 mv init* ../../data; mv l_setup ../../data
 mv l_stderr ../../data  # yambo 4.1
# mv l-p2y ../../data     # yambo 4.4
 echo "Done"
 echo "End:"; date
##########################################################################################################

